# Generated by Django 4.2.5 on 2023-09-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('login_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawal', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySetting',
            fields=[
                ('privacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('setting_update_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming_pre_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='NameSuggestion',
            fields=[
                ('suggestion_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggestion_name', models.TextField()),
                ('suggestion_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming_pre_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_file_name', models.TextField()),
                ('image_upload_date', models.DateTimeField()),
                ('image_url', models.TextField()),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming_pre_app.namesuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming_pre_app.user')),
            ],
        ),
    ]
